"""Initial migration

Revision ID: 6ba5eb6246df
Revises: cd5ce67cd167
Create Date: 2024-10-01 15:20:31.488705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba5eb6246df'
down_revision = 'cd5ce67cd167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('behavior_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('video_path')
        batch_op.drop_column('message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('video_path', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('timestamp',
               existing_type=sa.String(length=100),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('location')
        batch_op.drop_column('behavior_type')

    # ### end Alembic commands ###
