"""Add video_path column to alert table.

Revision ID: cd5ce67cd167
Revises: f590ffd114eb
Create Date: 2024-09-29 10:11:20.653853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd5ce67cd167'
down_revision = 'f590ffd114eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_path', sa.String(length=200), nullable=True))
        batch_op.drop_column('frame')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frame', sa.BLOB(), nullable=True))
        batch_op.drop_column('video_path')

    # ### end Alembic commands ###
